cleaning workflow plus compose file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -44,7 +44,6 @@ jobs:
 
       - name: Build ThingsBoard
         run: mvn clean install -DskipTests
-        #  run: mvn -T 2 clean install -DskipTests
 
       - name: Run common module tests
         run: cd common; mvn test; cd ..
@@ -52,65 +51,65 @@ jobs:
       - name: Run rule-engine-api module tests
         run: cd rule-engine; mvn test -pl rule-engine-api; cd ..
 
-  exec:
-    name: CD – Run ThingsBoard
-    runs-on: ubuntu-latest
-    needs: unit-tests
-
-    env:
-      MAVEN_OPTS: -Xmx1024m
-      SUREFIRE_JAVA_OPTS: -Xmx1200m -Xss256k -XX:+ExitOnOutOfMemoryError
-      NODE_OPTIONS: --max_old_space_size=4096
-
-    services:
-      postgres:
-        image: postgres:15
-        env:
-          POSTGRES_DB: thingsboard
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd="pg_isready -U postgres"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
-
-    steps:
-      - name: Checkout source
-        uses: actions/checkout@v4
-
-      - name: Set up Java 17
-        uses: actions/setup-java@v4
-        with:
-          distribution: corretto
-          java-version: "17"
-          cache: maven
-
-      - name: Build application
-        run: mvn -T 2 clean install -DskipTests
-
-      - name: Initialize database
-        run: |
-          java -cp application/target/thingsboard-4.4.0-SNAPSHOT-boot.jar \
-            -Dloader.main=org.thingsboard.server.ThingsboardInstallApplication \
-            -Dinstall.data_dir=application/target/data \
-            -Dinstall.load_demo=true \
-            -Dspring.jpa.hibernate.ddl-auto=none \
-            -Dinstall.upgrade=false \
-            -Dspring.datasource.url=jdbc:postgresql://localhost:5432/thingsboard \
-            -Dspring.datasource.username=postgres \
-            -Dspring.datasource.password=postgres \
-            org.springframework.boot.loader.launch.PropertiesLauncher
-
-      - name: Run ThingsBoard
-        run: |
-          java -jar application/target/thingsboard-4.4.0-SNAPSHOT-boot.jar \
-            --spring.datasource.url=jdbc:postgresql://localhost:5432/thingsboard \
-            --spring.datasource.username=postgres \
-            --spring.datasource.password=postgres
-          sleep 60
-
-      - name: Verify application is running
-        run: curl -f http://localhost:8080 || exit 1
+  # exec:
+  #   name: CD – Run ThingsBoard
+  #   runs-on: ubuntu-latest
+  #   needs: unit-tests
+#
+#   env:
+#     MAVEN_OPTS: -Xmx1024m
+#     SUREFIRE_JAVA_OPTS: -Xmx1200m -Xss256k -XX:+ExitOnOutOfMemoryError
+#     NODE_OPTIONS: --max_old_space_size=4096
+#
+#   services:
+#     postgres:
+#       image: postgres:15
+#       env:
+#         POSTGRES_DB: thingsboard
+#         POSTGRES_USER: postgres
+#         POSTGRES_PASSWORD: postgres
+#       ports:
+#         - 5432:5432
+#       options: >-
+#         --health-cmd="pg_isready -U postgres"
+#         --health-interval=10s
+#         --health-timeout=5s
+#         --health-retries=5
+#
+#   steps:
+#     - name: Checkout source
+#       uses: actions/checkout@v4
+#
+#     - name: Set up Java 17
+#       uses: actions/setup-java@v4
+#       with:
+#         distribution: corretto
+#         java-version: "17"
+#         cache: maven
+#
+#     - name: Build application
+#       run: mvn -T 2 clean install -DskipTests
+#
+#     - name: Initialize database
+#       run: |
+#         java -cp application/target/thingsboard-4.4.0-SNAPSHOT-boot.jar \
+#           -Dloader.main=org.thingsboard.server.ThingsboardInstallApplication \
+#           -Dinstall.data_dir=application/target/data \
+#           -Dinstall.load_demo=true \
+#           -Dspring.jpa.hibernate.ddl-auto=none \
+#           -Dinstall.upgrade=false \
+#           -Dspring.datasource.url=jdbc:postgresql://localhost:5432/thingsboard \
+#           -Dspring.datasource.username=postgres \
+#           -Dspring.datasource.password=postgres \
+#           org.springframework.boot.loader.launch.PropertiesLauncher
+#
+#     - name: Run ThingsBoard
+#       run: |
+#         java -jar application/target/thingsboard-4.4.0-SNAPSHOT-boot.jar \
+#           --spring.datasource.url=jdbc:postgresql://localhost:5432/thingsboard \
+#           --spring.datasource.username=postgres \
+#           --spring.datasource.password=postgres
+#         sleep 60
+#
+#     - name: Verify application is running
+#       run: curl -f http://localhost:8080 || exit 1
